nonsky_dir: D:\workplace\dataset\Heshan_imgset\256x256\non_sky
#nonsky_dir: ../../Heshan_imgset/256x256/non_sky

train:
  epochs: 30
  pretrained: True
  batch: 16
  imgsize: 224

val:
  model: VGG16/VGG16_100.pt
