---
project: im_invironment
experiment_desc: 'experiment1'

nonsky_dir: D:\workplace\dataset\Heshan_imgset\256x256\non_sky
# nonsky_dir: F:\workplace\public_dataset\Heshan_imgset\256x256\non_sky
# nonsky_dir: ../Heshan_imgset/256x256/non_sky

data_split:
  split_date: 1107
  split_back: False

model:
  g_name: resnet34
  out_features: 1

train:
  pretrained: True

test:
  model_path: ../data/Resnet/resnet34_re.h5
  crop_img_blocks: 20

num_epochs: 3
batches_per_epoch: 10  # min(*, len(run_dataset))
batch_size: 16
image_size: [224, 224]

optimizer:
  name: sgd
  lr: 0.0005
  momentum: 0.9