# nonsky_dir: D:\workplace\dataset\Heshan_imgset\256x256\non_sky
nonsky_dir: F:\workplace\public_dataset\Heshan_imgset\256x256\non_sky
# nonsky_dir: ../../Heshan_imgset/256x256/non_sky

train:
  epochs: 30
  pretrained: True
  batch: 16
  imgsize: 224

val:
  imgsize: 224
  batch: 16
  model: data/pth/vgg16_bn.pth

data_split:
  split_date: 1107
  split_back: True
