---
project: im_invironment
experiment_desc: 'exp_resnet34_classify_128'

nonsky_dir: D:\workplace\dataset\Heshan_imgset\256x256\non_sky
# nonsky_dir: F:\workplace\public_dataset\Heshan_imgset\256x256\non_sky
# nonsky_dir: ../Heshan_imgset/256x256/non_sky

data_split:
  split_date: 1107  # need to delete
  val_ratio: 0.2
  split_back: False

model:
  g_name: resnet101
  out_features: 1

train:
  pretrained: False  # Remember to set false if create a new training process
  start_epoch: 30
  model_path: data/exp_resnet34_classify_128/last_exp_resnet34_classify_128.h5

test:
  model_path: ../data/Resnet/resnet34_re.h5
  crop_img_blocks: 20

num_epochs: 3           # 10 -> overfit?
batches_per_epoch: 1    # min(*, len(run_dataset))
batch_size: 16
image_size: [128, 128]
transform_first: RandomCrop

optimizer:
  name: sgd
  lr: 0.0001  # 0.0005 -> overfit?
  momentum: 0.9